services:
  muhomu:
    build: .
    ports:
      - "4444:4444"
    volumes:
      - ./data:/data:z
    restart: unless-stopped
    environment:
      - PORT=4444
      - DATA_DIR=/data
      - STATIC_DIR=/app/static
